storage:
  path: ./data/

watchlist:
  stocks:
    AAPL:
      exchange: NASDAQ
      currency: USD
    GOOGL:
      exchange: NASDAQ
      currency: USD
    MSFT:
      exchange: NASDAQ
      currency: USD
    AMZN:
      exchange: NASDAQ
      currency: USD
    TSLA:
      exchange: NASDAQ
      currency: USD